package com.slin.git.entity

import com.google.gson.annotations.SerializedName

data class UserInfo(
    val login: String,
    val id: Int,
    @SerializedName("node_id") val nodeId: String,
    @SerializedName("avatar_url") val avatarUrl: String,
    @SerializedName("gravatar_id") val gravatarId: String,
    val url: String,
    @SerializedName("html_url") val htmlUrl: String,
    @SerializedName("followers_url") val followersUrl: String,
    @SerializedName("following_url") val followingUrl: String,
    @SerializedName("gists_url") val gistsUrl: String,
    @SerializedName("starred_url") val starredUrl: String,
    @SerializedName("subscriptions_url") val subscriptionsUrl: String,
    @SerializedName("organizations_url") val organizationsUrl: String,
    @SerializedName("repos_url") val reposUrl: String,
    @SerializedName("events_url") val eventsUrl: String,
    @SerializedName("received_events_url") val receivedEventsUrl: String,
    val type: String,
    @SerializedName("site_admin") val siteAdmin: String,
    val name: String,
    val company: String,
    val blog: String,
    val location: String,
    val email: String,
    val hireable: String,
    val bio: String,
    @SerializedName("public_repos") val publicRepos: Int,
    @SerializedName("public_gists") val publicGists: Int,
    val followers: Int,
    val following: Int,
    @SerializedName("created_at") val createdAt: String,
    @SerializedName("updated_at") val updatedAt: String,
    @SerializedName("private_gists") val privateGists: Int,
    @SerializedName("total_private_repos") val totalPrivateRepos: Int,
    @SerializedName("owned_private_repos") val ownedPrivateRepos: Int,
    @SerializedName("disk_usage") val diskUsage: Int,
    val collaborators: Int,
    @SerializedName("two_factor_authentication") val twoFactorAuthentication: Boolean
) {
    companion object {
        //{"login":"dxslin","id":12908813,"node_id":"MDQ6VXNlcjEyOTA4ODEz","avatar_url":"https://avatars3.githubusercontent.com/u/12908813?v=4","gravatar_id":"","url":"https://api.github.com/users/dxslin","html_url":"https://github.com/dxslin","followers_url":"https://api.github.com/users/dxslin/followers","following_url":"https://api.github.com/users/dxslin/following{/other_user}","gists_url":"https://api.github.com/users/dxslin/gists{/gist_id}","starred_url":"https://api.github.com/users/dxslin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dxslin/subscriptions","organizations_url":"https://api.github.com/users/dxslin/orgs","repos_url":"https://api.github.com/users/dxslin/repos","events_url":"https://api.github.com/users/dxslin/events{/privacy}","received_events_url":"https://api.github.com/users/dxslin/received_events","type":"User","site_admin":false,"name":"slin","company":null,"blog":"","location":"Chongqing","email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":11,"public_gists":0,"followers":1,"following":16,"created_at":"2015-06-16T08:41:53Z","updated_at":"2020-09-17T09:22:55Z","private_gists":0,"total_private_repos":4,"owned_private_repos":4,"disk_usage":184157,"collaborators":0,"two_factor_authentication":false,"plan":{"name":"free","space":976562499,"collaborators":0,"private_repos":10000}}
        val dxslin = UserInfo(
            login = "dxslin",
            id = 12908813,
            nodeId = "MDQ6VXNlcjEyOTA4ODEz",
            avatarUrl = "https://avatars3.githubusercontent.com/u/12908813?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/dxslin",
            htmlUrl = "https://github.com/dxslin",
            followersUrl = "https://api.github.com/users/dxslin/followers",
            followingUrl = "https://api.github.com/users/dxslin/following{/other_user}",
            gistsUrl = "https://api.github.com/users/dxslin/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/dxslin/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/dxslin/subscriptions",
            organizationsUrl = "https://api.github.com/users/dxslin/orgs",
            reposUrl = "https://api.github.com/users/dxslin/repos",
            eventsUrl = "https://api.github.com/users/dxslin/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/dxslin/received_events",
            type = "User",
            siteAdmin = "",
            name = "slin",
            company = "",
            blog = "",
            location = "Chongqing",
            email = "",
            hireable = "",
            bio = "",
            publicRepos = 11,
            publicGists = 0,
            followers = 1,
            following = 16,
            createdAt = "2015-06-16T08:41:53Z",
            updatedAt = "2020-09-17T09:22:55Z",
            privateGists = 0,
            totalPrivateRepos = 4,
            ownedPrivateRepos = 4,
            diskUsage = 184157,
            collaborators = 0,
            twoFactorAuthentication = false,
        )
    }
}

